<a href="https://colab.research.google.com/github/BarbyJRigoni/Aprendizaje-Automatico/blob/main/Semana_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Instancia de  Evaluación Espacio de entrega de tarea:
Imaginemos que eres un científico de datos que trabaja en un proyecto de análisis de mercado para una empresa de comercio electrónico. Tu objetivo es recopilar, procesar y analizar datos de ventas que provienen de diferentes fuentes en varios formatos. Para lograrlo, debes diseñar un proceso de importación de datos utilizando PANDAS.

Datos de Prueba:

1. Archivo CSV (Comma-Separated Values): Tienes un archivo llamado "ventas.csv" que contiene información sobre las ventas de productos. Cada fila representa una venta y contiene varias columnas con los datos sobre las ventas.

2. Archivo JSON (JavaScript Object Notation): También tienes un archivo llamado "clientes.json" con datos de los clientes que realizaron las compras. Cada objeto JSON representa un cliente y contiene sus datos.



3. Hoja de Cálculo Excel: Existe un archivo llamado "inventario.xlsx" con información sobre el inventario de productos. La hoja de cálculo contiene varias columnas con datos sobre los productos.

    

Tu tarea es utilizar la librería PANDAS para importar estos datos desde los diferentes formatos (CSV, JSON y Excel), combinarlos en una estructura de datos adecuada y realizar las siguientes acciones:

1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.

2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.

3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.

***1. Cargar los datos de ventas desde el archivo CSV y mostrar una vista previa de las primeras filas.***

In [2]:
import pandas as pd
dat_csv = pd.read_csv("/content/drive/MyDrive/Aprendizaje Automático/archivos semana 2/ventas (1).csv")
dat_csv.head()

   id_venta       fecha  producto  cantidad  precio_unitario
0         1  2026-01-10  Notebook         2             1200
1         2  2026-01-12     Mouse         5               25
2         3  2026-01-15   Teclado         3               45
3         4  2026-01-18   Monitor         1              300

***2. Cargar los datos de clientes desde el archivo JSON y mostrar la cantidad total de clientes.***

In [3]:
import pandas as pd
movies_json = pd.read_json("/content/drive/MyDrive/Aprendizaje Automático/archivos semana 2/clientes.json")
movies_json.head()

   id_cliente        nombre             email   telefono
0           1    Juan Pérez    juan@email.com  123456789
1           2   María López   maria@email.com  987654321
2           3  Carlos Gómez  carlos@email.com  456123789

*Mostrar la cantidad de Clientes*

In [4]:
print("Cantidad de clientes: ",len(movies_json))

Cantidad de clientes:  3

***3. Cargar los datos de inventario desde la hoja de cálculo Excel y calcular el promedio de stock disponible para todos los productos.***

In [5]:
import pandas as pd
dat_excel = pd.read_excel("/content/drive/MyDrive/Aprendizaje Automático/archivos semana 2/inventario.xlsx")
dat_excel.head()

   id_producto    nombre    categoria  stock  precio
0            1  Notebook  Electrónica     10    1200
1            2     Mouse   Accesorios     50      25
2            3   Teclado   Accesorios     30      45
3            4   Monitor  Electrónica     15     300

*Promedio de Stock*

In [6]:
# Calcular promedio de la columna stock
promedio_stock = dat_excel['stock'].mean()

print("Promedio de stock:", promedio_stock)

Promedio de stock: 26.25